default: &default
  adapter: mysql2
  encoding: 'utf8'
  database: users_crud
  pool: 5
  username: root
  password: password
  host: localhost

development:
  <<: *default

test:
  <<: *default
  database: users_crud_test

production:
  <<: *default
